version: '3'
services:
  service_one:
    build:
      context: ./services/service_one
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
      - mongodb
  service_two:
    build:
      context: ./services/service_two
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
      - mongodb
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
